fixtures:
  repositories:
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.1.0"
    duplicity:
      repo: "https://github.com/tohuwabohu/puppet-duplicity.git"
      ref: "848b43eec9c836a442fa303f7b7d7e26f53e64bd"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.1.0"
  symlinks:
    duplicity_postgresql: "#{source_dir}"

