fixtures:
  repositories:
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.1.0"
    duplicity:
      repo: "https://github.com/tohuwabohu/tohuwabohu-duplicity.git"
      ref: "52d785b3a68399cda1950a33c21c3a046831d213"
    puppi:
      repo: "https://github.com/example42/puppi.git"
      ref: "v2.1.9"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.1.0"
  symlinks:
    duplicity_postgresql: "#{source_dir}"

