name 'tohuwabohu-duplicity_postgresql'
version '1.0.0'
source 'https://github.com/tohuwabohu/tohuwabohu-duplicity_postgresql.git'
project_page 'https://github.com/tohuwabohu/tohuwabohu-duplicity_postgresql'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Backup and restore PostgreSQL databases based on duplicity'
description ''

dependency 'example42/puppi', '2.x'
dependency 'puppetlabs/concat', '>= 1.1.0 < 2.0.0'
dependency 'puppetlabs/stdlib', '4.x'
